force-app/main/default/objects/ProductTable__c/ProductTable__c.object-meta.xml
<CustomObject>
    <label>ProductTable</label>
    <nameField>
        <label>Product Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductTable__c/fields/AddedDate__c.field-meta.xml
<CustomField>
    <fullName>AddedDate__c</fullName>
    <label>AddedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/ProductTable__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductTable__c/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProductTable__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ProductTable__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>ProductType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductTypePicklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductTable__c/fields/ReleaseDate__c.field-meta.xml
<CustomField>
    <fullName>ReleaseDate__c</fullName>
    <label>ReleaseDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/ProductTypePicklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Camera</fullName>
    </customValue>
    <customValue>
        <fullName>Clock</fullName>
    </customValue>
    <customValue>
        <fullName>Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Tablet</fullName>
    </customValue>
    <masterLabel>ProductTypePicklist</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProductTableController.cls
public with sharing class ProductTableController {
    @AuraEnabled
    public static List<ProductTable__c> getProducts() {
        return [
            SELECT 
                Id, 
                Name, 
                Amount__c, 
                Price__c, 
                ProductType__c, 
                ReleaseDate__c, 
                Available__c
            FROM ProductTable__c
            WITH SECURITY_ENFORCED
            ORDER BY AddedDate__c DESC
            LIMIT 2000
        ];
    }
}    