force-app/main/default/objects/ProductTable__c/ProductTable__c.object-meta.xml
<CustomObject>
    <label>ProductTable</label>
    <nameField>
        <label>Product Table Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Product Tables</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ProductTable__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ProductTable__c/fields/Available__c.field-meta.xml
<CustomField>
    <fullName>Available__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Available</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ProductTable__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/ProductTable__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>ProductType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductTypePicklist</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/ProductTable__c/fields/ReleaseDate__c.field-meta.xml
<CustomField>
    <fullName>ReleaseDate__c</fullName>
    <label>ReleaseDate</label>
    <type>Date</type>
</CustomField>

force-app/main/default/globalValueSets/ProductTypePicklist.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Camera</fullName>
    </customValue>
    <customValue>
        <fullName>Clock</fullName>
    </customValue>
    <customValue>
        <fullName>Phone</fullName>
    </customValue>
    <customValue>
        <fullName>Tablet</fullName>
    </customValue>
    <masterLabel>ProductTypePicklist</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/TestProductTableApplication.cls
/*
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an org are executed whenever Apex code is deployed
 * to a production org to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production org. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the org size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestProductTableApplication {

   @isTest
    static void addTest() {
        String searchTerm = 'Product';
        String orderField = 'Name';
        String orderDirection = 'asc';
        Integer pageSize = 5;
        Integer pageNumber = 0;

        String addedRecord = '{"Name":"New Product","Amount__c":50,"Price__c":5000,"ProductType__c":"Phone","ReleaseDate__c":"2025-05-01"}';
        String toCheck = '"Name":"New Product","Amount__c":50,"Price__c":5000,"ProductType__c":"Phone","ReleaseDate__c":"2025-05-01","Available__c":true';

        Test.startTest();
        ProductTableController.addProduct(addedRecord);
        ProductTableController.ResultData result = 
            ProductTableController.getProducts(searchTerm, orderField, orderDirection, pageSize, pageNumber);
        Test.stopTest();

        String res = JSON.serialize(result.products);
        boolean check = res.contains(toCheck);
        Assert.isTrue(check, 'addTest failure');

    }

    @isTest
    static void editTest() {
        ProductTable__c newProduct = new ProductTable__c(
            Name = 'Default Product',
            Amount__c = 50,
            Price__c = 5000,
            ProductType__c = 'Phone',
            ReleaseDate__c = Date.valueOf('2025-05-01')
        );

        insert newProduct;

        String searchTerm;
        String orderField;
        String orderDirection;
        Integer pageSize = 5;
        Integer pageNumber = 0;

        String editedRecord = '{"Id":'+JSON.serialize(newProduct.Id)+',"Name":"Edited Product","Amount__c":0,"Price__c":4000,"ProductType__c":"Camera","ReleaseDate__c":"2025-05-03"}';
        String toCheck = '"Name":"Edited Product","Amount__c":0,"Price__c":4000,"ProductType__c":"Camera","ReleaseDate__c":"2025-05-03","Available__c":false'; 

        Test.startTest();
            ProductTableController.editProduct(editedRecord);
            ProductTableController.ResultData result = 
            ProductTableController.getProducts(searchTerm, orderField, orderDirection, pageSize, pageNumber);
        Test.stopTest();

        String res = JSON.serialize(result.products);
        boolean check = res.contains(toCheck);
        Assert.isTrue(check, 'editTest failure');
    }

    @isTest
    static void deleteTest() {
        ProductTable__c newProduct = new ProductTable__c(
            Name = 'Default Product',
            Amount__c = 50,
            Price__c = 5000,
            ProductType__c = 'Phone',
            ReleaseDate__c = Date.valueOf('2025-05-01')
        );

        insert newProduct;

        String searchTerm;
        String orderField;
        String orderDirection;
        Integer pageSize = 5;
        Integer pageNumber = 0;

        String deletedRecord = '{"Id":'+JSON.serialize(newProduct.Id)+',"Name":"Default Product","Amount__c":50,"Price__c":5000,"ProductType__c":"Phone","ReleaseDate__c":"2025-05-01"}';
        String toCheck = '"Name":"Default Product"'; 

        Test.startTest();
            ProductTableController.deleteProduct(deletedRecord);
            ProductTableController.ResultData result = 
            ProductTableController.getProducts(searchTerm, orderField, orderDirection, pageSize, pageNumber);
        Test.stopTest();

        String res = JSON.serialize(result.products);
        boolean check = res.contains(toCheck);
        Assert.isFalse(check, 'editTest failure');

    }
}